name: ZPixelReboot
main: org.ru.shad0vsky.zpixel.ZPixelReboot

version    : '${project.version}'
api-version: '1.17'

prefix : ZPIXEL // 1.17.1
authors: [ shad0vsky, 1ServiS1 ]
website: https://vk.com/z.pixel

description: >
  ZPixel of first version is copy of popular MMO in SNG countries. We will update it, when will have a money on own experiments.

database: true
